version: '3.8'

services:
  # 1. Наше приложение
  app:
    build: .                 # Собираем из текущей папки (Dockerfile)
    ports:
      - "8080:8080"          # Пробрасываем порт наружу
    depends_on:
      - db                   # Ждем, пока запустится база
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/employee_db  # <-- СМОТРИ СЮДА
      - JDBC_USER=postgres
      - JDBC_PASSWORD=1111   # Твой пароль от БД (проверь, какой у тебя!)

  # 2. База данных (в отдельном контейнере)
  db:
    image: postgres:15       # Скачиваем готовый Postgres
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111 # Твой пароль
    ports:
      - "5432:5432"          # Чтобы ты мог подключаться через DBeaver с компа