version: '3.8'

services:
  # 1. Наше приложение
  app:
    #build: .                # <-- БОЛЬШЕ НЕ СОБИРАЕМ ЛОКАЛЬНО
    image: dmitryderkach/employee-manager-app:latest
    ports:
      - "8080:8080"          # Пробрасываем порт наружу
    depends_on:
      - db                   # Ждем, пока запустится база
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/employee_db  # <-- СМОТРИ СЮДА
      - JDBC_USER=postgres
      - JDBC_PASSWORD=1111   # Твой пароль от БД (проверь, какой у тебя!)
    # --- НАЧАЛО ВСТАВКИ ---
    # Инструкция для Докера: как проверить, что приложение живо
    healthcheck:
      # Команда: Пытаемся скачать главную страницу. Если успех (200 OK) - мы живы.
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      interval: 5s    # Как часто проверять (раз в 5 секунд)
      timeout: 5s     # Сколько ждать ответа
      retries: 15     # Сколько раз попробовать перед тем как сдаться (итого макс 75 сек)
      start_period: 10s # Дать 10 сек на старт Java-машины перед первой проверкой
    # --- КОНЕЦ ВСТАВКИ ---

  # 2. База данных (в отдельном контейнере)
  db:
    image: postgres:15       # Скачиваем готовый Postgres
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111 # Твой пароль
    ports:
      - "5432:5432"          # Чтобы ты мог подключаться через DBeaver с компа